trigger:
- trunk
- dev
variables:
- name: versionStamp
  value: '[Build: $(Build.BuildNumber). Commit: $(Build.SourceVersion)]'
pool:
  vmImage: "ubuntu-latest"
steps:
- task: NodeTool@0
  displayName: 'Use Node 14'
  inputs:
    versionSpec: 14.x
- task: replacetokens@3
  displayName: 'Replace tokens in **/plugin.php'
  inputs:
    targetFiles: '**/plugin.php'
    escapeType: none
- task: Npm@1
  inputs:
    command: 'install'
- task: Npm@1
  displayName: 'npm run build'
  inputs:
    command: custom
    verbose: false
    customCommand: 'run build'
- task: DeleteFiles@1
  displayName: 'Delete NPM Stuff'
  inputs:
    Contents: |
     node_modules
     package*
     gulpfile*
     readme*
- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: mayflower-blocks'
  inputs:
    PathtoPublish: ./
    ArtifactName: 'mayflower-blocks'
