trigger:
  branches:
    include:
      - trunk
  tags:
    include:
      - 'v*'
  paths:
    exclude:
      - azure-pipelines.yml
      - azure-pipelines-release.yml

pr:
  branches:
    include:
      - trunk
      - release-v*
      - hotfix-v*

resources:
  repositories:
    - repository: templates
      type: github
      name: BellevueCollege/bc-wordpress-devops-templates
      endpoint: github-service-connection

variables:
  versionStamp: '[Build: $(Build.BuildNumber). Commit: $(Build.SourceVersion)]'

extends:
  template: templates/ci/plugin-ci.yml@templates
  parameters:
    # WordPress plugins directory slug (not the GitHub repo name).
    pluginName: 'mayflower-blocks-g4'
    runComposer: false
    testEnvironments:
      - name: KinstaCstage
        displayName: 'Kinsta: CStage'
        environment: kinsta-cstage
        sshServiceConnection: cstage
        variableGroup: kinsta-cstage
    buildSteps:
      - task: replacetokens@6
        displayName: 'Replace tokens in plugin.php'
        inputs:
          sources: '**/plugin.php'
          escape: off
      - task: Npm@1
        displayName: 'NPM Build'
        inputs:
          command: custom
          customCommand: 'run build'
