trigger:
- trunk
- dev
variables:
- name: versionStamp
  value: '[Build: $(Build.BuildNumber). Commit: $(Build.SourceVersion)]'
- name: npm_config_cache
  value: $(Pipeline.Workspace)/.npm
pool:
  vmImage: "ubuntu-latest"
steps:
- task: replacetokens@6
  displayName: 'Replace tokens in **/plugin.php'
  inputs:
    sources: '**/plugin.php'
    escape: off
- task: UseNode@1
  inputs:
    version: '24.x'
  displayName: 'Install Node.js 24'
- script: npm install -g npm@11.16.0
  displayName: 'Force functinal NPM version'
- script: |
    node --version
    npm --version
  displayName: 'Check Node/npm versions'
- task: Cache@2
  inputs:
    key: 'npm | "$(Agent.OS)" | package-lock.json'
    restoreKeys: |
      npm | "$(Agent.OS)"
    path: $(npm_config_cache)
- task: Npm@1
  inputs:
    command: 'ci'
  displayName: 'NPM Clean Install'
- task: Npm@1
  displayName: 'npm run build'
  inputs:
    command: custom
    verbose: false
    customCommand: 'run build'
- task: Npm@1
  displayName: 'Reinstall production dependencies only'
  inputs:
    command: 'custom'
    customCommand: 'ci --omit=dev'
- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: mayflower-blocks'
  inputs:
    PathtoPublish: ./
    ArtifactName: 'mayflower-blocks'
